---
- hosts: XR
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
  - name: get IOS-XR running configuration
    cisco.iosxr.iosxr_facts:
      gather_subset: all
      gather_network_resources: all
      host: '{{ ansible_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
    register: output
  - debug: var=output.stdout_lines

