---
- hosts: XR
  gather_facts: no
  connection: paramiko
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  tasks:
  - name: get IOS-XR running configuration
    cisco.iosxr.iosxr_facts:
      gather_subset: all
      gather_network_resources: all
    register: output
  - debug: var=output.stdout_lines

