---
- hosts: XR
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
  - name: get IOS-XR running configuration
    cisco.iosxr.iosxr_facts:
      gather_subset: all
      gather_network_resources: all
    register: output
  - debug: var=output.stdout_lines

